// Code generated by domaingen from api/domain.yaml. DO NOT EDIT.

package regionkit

import "strings"

// RegionNames lists every region api/domain.yaml declares, in
// declaration order.
var RegionNames = []string{"ntsc_u", "ntsc_j", "pal", "korea", "brazil", "china", "region_free"}

// regionClassTable backs RegionClass.
var regionClassTable = map[string]string{
	"ntsc_u":      "base",
	"ntsc_j":      "jp",
	"pal":         "pal",
	"korea":       "base",
	"brazil":      "base",
	"china":       "base",
	"region_free": "base",
}

// RegionClass maps a known entry region onto the console-listing
// class that prices it, mirroring api/domain.yaml's regions[].class;
// an unrecognized region defaults to "base".
func RegionClass(region string) string {
	if c, ok := regionClassTable[region]; ok {
		return c
	}
	return "base"
}

// LocalizationChains maps an entry region to its ordered IGDB
// localization identifiers; a region with no chain is absent from
// this map.
var LocalizationChains = map[string][]string{
	"ntsc_j": {"ja-JP"},
	"pal":    {"EU"},
	"korea":  {"ko-KR"},
	"brazil": {"pt-BR"},
	"china":  {"zh-CN", "zh-TW"},
}

// JPConsoleNames are PriceCharting's distinct-name JP market consoles
// (the ones filed without a "jp " prefix).
var JPConsoleNames = map[string]bool{
	"famicom":             true,
	"super famicom":       true,
	"famicom disk system": true,
}

// ConsoleRegion classifies a PriceCharting console-name into the
// region class its listings price: "pal " prefix, "jp " prefix or a
// distinct JP market name, else base.
func ConsoleRegion(consoleName string) string {
	c := strings.ToLower(strings.TrimSpace(consoleName))
	switch {
	case strings.HasPrefix(c, "pal "):
		return "pal"
	case strings.HasPrefix(c, "jp "), JPConsoleNames[c]:
		return "jp"
	default:
		return "base"
	}
}

// TwinPlatformIDs pairs an IGDB platform id with its JP-regional twin
// in both directions: looking up either side of a pair returns the
// other.
var TwinPlatformIDs = map[int64]int64{
	99: 18,
	18: 99,
	58: 19,
	19: 58,
}

// DigitalOnlyPlatformIDs are the IGDB platforms that never carried
// physical media; the catalog hides them while entries are physical-only.
var DigitalOnlyPlatformIDs = map[int64]bool{
	34:  true, // Android
	39:  true, // iOS
	73:  true, // BlackBerry OS
	74:  true, // Windows Phone
	405: true, // Windows Mobile
	417: true, // Palm OS
	472: true, // visionOS
	47:  true, // Virtual Console
	82:  true, // Web browser
	113: true, // OnLive Game System
	132: true, // Amazon Fire TV
	170: true, // Google Stadia
	203: true, // Google Stadia duplicate row
	372: true, // OOParts
	389: true, // AirConsole
	161: true, // Windows Mixed Reality
	162: true, // Oculus VR
	163: true, // SteamVR
	164: true, // Daydream
	384: true, // Oculus Quest
	385: true, // Oculus Rift
	386: true, // Meta Quest 2
	387: true, // Oculus Go
	388: true, // Gear VR
	471: true, // Meta Quest 3
	72:  true, // Ouya
	240: true, // Zeebo
	55:  true, // Legacy Mobile Device
	381: true, // Playdate
	377: true, // Plug & Play
	382: true, // Intellivision Amico
	438: true, // Arduboy
	440: true, // Visual Memory Unit
	441: true, // PocketStation
}

// ReleaseRegionNames maps IGDB's release_region vendor enum onto its
// canonical name; an id absent from this map is unknown to this service.
var ReleaseRegionNames = map[int]string{
	1:  "europe",
	2:  "north_america",
	3:  "australia",
	4:  "new_zealand",
	5:  "japan",
	6:  "china",
	7:  "asia",
	8:  "worldwide",
	9:  "korea",
	10: "brazil",
}
