// Command domaingen runs two codegen jobs from api/domain.yaml and
// api/bundled/bff.yaml: libs/go/regionkit's Go table, a frontend TS
// file, and frontend/src/gen/facets.ts (schema constraint values).
// `task gen` runs both; CI fails if a generated file diverges.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// domain is api/domain.yaml's parsed shape; slice order is document
// order, which both emitters rely on for deterministic output.
type domain struct {
	Regions        []regionRow        `yaml:"regions"`
	JPConsoleNames []string           `yaml:"jp_console_names"`
	Platforms      []platformRow      `yaml:"platforms"`
	DigitalOnly    []digitalOnlyRow   `yaml:"digital_only_platforms"`
	ReleaseRegions []releaseRegionRow `yaml:"release_regions"`
}

// regionRow is one entry in domain.yaml's regions list; LocalizationChain
// is empty for ntsc_u/region_free, and emitters skip such rows entirely.
type regionRow struct {
	Name              string   `yaml:"name"`
	Class             string   `yaml:"class"`
	LocalizationChain []string `yaml:"localization_chain"`
}

// platformRow is one entry in domain.yaml's platforms list; Name is
// descriptive only, and TwinIGDBID 0 means no JP-regional twin.
type platformRow struct {
	IGDBID     int64  `yaml:"igdb_id"`
	Name       string `yaml:"name"`
	Region     string `yaml:"region"`
	TwinIGDBID int64  `yaml:"twin_igdb_id"`
}

// digitalOnlyRow is one entry in domain.yaml's digital_only_platforms
// list; Name is descriptive only.
type digitalOnlyRow struct {
	IGDBID int64  `yaml:"igdb_id"`
	Name   string `yaml:"name"`
}

// releaseRegionRow decodes one release_regions entry: IGDB's enum id to
// a name, plus EntryRegion (empty when no 1:1 mapping, e.g. worldwide).
type releaseRegionRow struct {
	IGDBID      int    `yaml:"igdb_id"`
	Name        string `yaml:"name"`
	EntryRegion string `yaml:"entry_region"`
}

// parseDomain decodes domain.yaml. KnownFields is on: an unrecognized
// key fails the parse instead of vanishing silently.
func parseDomain(data []byte) (*domain, error) {
	dec := yaml.NewDecoder(bytes.NewReader(data))
	dec.KnownFields(true)
	var d domain
	if err := dec.Decode(&d); err != nil {
		return nil, fmt.Errorf("parsing domain yaml: %w", err)
	}
	return &d, nil
}

// generateGo renders libs/go/regionkit/tables_gen.go for package pkg,
// built as plain text then run through go/format for canonical output.
func generateGo(d *domain, pkg string) ([]byte, error) {
	var b strings.Builder

	b.WriteString("// Code generated by domaingen from api/domain.yaml. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	b.WriteString("import \"strings\"\n\n")

	b.WriteString("// RegionNames lists every region api/domain.yaml declares, in\n// declaration order.\n")
	b.WriteString("var RegionNames = []string{")
	for i, r := range d.Regions {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(&b, "%q", r.Name)
	}
	b.WriteString("}\n\n")

	b.WriteString("// regionClassTable backs RegionClass.\n")
	b.WriteString("var regionClassTable = map[string]string{\n")
	for _, r := range d.Regions {
		fmt.Fprintf(&b, "\t%q: %q,\n", r.Name, r.Class)
	}
	b.WriteString("}\n\n")

	b.WriteString("// RegionClass maps a known entry region onto the console-listing\n")
	b.WriteString("// class that prices it, mirroring api/domain.yaml's regions[].class;\n")
	b.WriteString("// an unrecognized region defaults to \"base\".\n")
	b.WriteString("func RegionClass(region string) string {\n")
	b.WriteString("\tif c, ok := regionClassTable[region]; ok {\n\t\treturn c\n\t}\n")
	b.WriteString("\treturn \"base\"\n}\n\n")

	b.WriteString("// LocalizationChains maps an entry region to its ordered IGDB\n")
	b.WriteString("// localization identifiers; a region with no chain is absent from\n")
	b.WriteString("// this map.\n")
	b.WriteString("var LocalizationChains = map[string][]string{\n")
	for _, r := range d.Regions {
		if len(r.LocalizationChain) == 0 {
			continue
		}
		fmt.Fprintf(&b, "\t%q: {", r.Name)
		for i, id := range r.LocalizationChain {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(&b, "%q", id)
		}
		b.WriteString("},\n")
	}
	b.WriteString("}\n\n")

	b.WriteString("// JPConsoleNames are PriceCharting's distinct-name JP market consoles\n")
	b.WriteString("// (the ones filed without a \"jp \" prefix).\n")
	b.WriteString("var JPConsoleNames = map[string]bool{\n")
	for _, n := range d.JPConsoleNames {
		fmt.Fprintf(&b, "\t%q: true,\n", n)
	}
	b.WriteString("}\n\n")

	b.WriteString("// ConsoleRegion classifies a PriceCharting console-name into the\n")
	b.WriteString("// region class its listings price: \"pal \" prefix, \"jp \" prefix or a\n")
	b.WriteString("// distinct JP market name, else base.\n")
	b.WriteString("func ConsoleRegion(consoleName string) string {\n")
	b.WriteString("\tc := strings.ToLower(strings.TrimSpace(consoleName))\n")
	b.WriteString("\tswitch {\n")
	b.WriteString("\tcase strings.HasPrefix(c, \"pal \"):\n\t\treturn \"pal\"\n")
	b.WriteString("\tcase strings.HasPrefix(c, \"jp \"), JPConsoleNames[c]:\n\t\treturn \"jp\"\n")
	b.WriteString("\tdefault:\n\t\treturn \"base\"\n")
	b.WriteString("\t}\n}\n\n")

	b.WriteString("// TwinPlatformIDs pairs an IGDB platform id with its JP-regional twin\n")
	b.WriteString("// in both directions: looking up either side of a pair returns the\n")
	b.WriteString("// other.\n")
	b.WriteString("var TwinPlatformIDs = map[int64]int64{\n")
	for _, p := range d.Platforms {
		if p.TwinIGDBID == 0 {
			continue
		}
		fmt.Fprintf(&b, "\t%d: %d,\n", p.IGDBID, p.TwinIGDBID)
		fmt.Fprintf(&b, "\t%d: %d,\n", p.TwinIGDBID, p.IGDBID)
	}
	b.WriteString("}\n\n")

	b.WriteString("// DigitalOnlyPlatformIDs are the IGDB platforms that never carried\n")
	b.WriteString("// physical media; the catalog hides them while entries are physical-only.\n")
	b.WriteString("var DigitalOnlyPlatformIDs = map[int64]bool{\n")
	for _, p := range d.DigitalOnly {
		fmt.Fprintf(&b, "\t%d: true, // %s\n", p.IGDBID, p.Name)
	}
	b.WriteString("}\n\n")

	b.WriteString("// ReleaseRegionNames maps IGDB's release_region vendor enum onto its\n")
	b.WriteString("// canonical name; an id absent from this map is unknown to this service.\n")
	b.WriteString("var ReleaseRegionNames = map[int]string{\n")
	for _, r := range d.ReleaseRegions {
		fmt.Fprintf(&b, "\t%d: %q,\n", r.IGDBID, r.Name)
	}
	b.WriteString("}\n")

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("formatting generated Go: %w", err)
	}
	return formatted, nil
}

// tsString renders s as a single-quoted TS string literal, escaping
// backslashes and quotes regardless of how trusted the input looks.
func tsString(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `'`, `\'`)
	return "'" + s + "'"
}

// generateTS renders frontend/src/gen/domain.ts; with no TS formatter
// available, the builder emits already-canonical 2-space output directly.
func generateTS(d *domain) ([]byte, error) {
	var b strings.Builder

	b.WriteString("// Code generated by domaingen from api/domain.yaml. DO NOT EDIT.\n\n")

	b.WriteString("export const REGIONS = [")
	for i, r := range d.Regions {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(tsString(r.Name))
	}
	b.WriteString("] as const\n\n")

	b.WriteString("export type Region = (typeof REGIONS)[number]\n\n")

	b.WriteString("export const REGION_CLASS: Record<string, 'base' | 'jp' | 'pal'> = {\n")
	for _, r := range d.Regions {
		fmt.Fprintf(&b, "  %s: %s,\n", r.Name, tsString(r.Class))
	}
	b.WriteString("}\n\n")

	b.WriteString("export const LOCALIZATION_CHAINS: Record<string, string[]> = {\n")
	for _, r := range d.Regions {
		if len(r.LocalizationChain) == 0 {
			continue
		}
		fmt.Fprintf(&b, "  %s: [", r.Name)
		for i, id := range r.LocalizationChain {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(tsString(id))
		}
		b.WriteString("],\n")
	}
	b.WriteString("}\n\n")

	b.WriteString("export const JP_CONSOLE_NAMES = new Set([")
	for i, n := range d.JPConsoleNames {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(tsString(n))
	}
	b.WriteString("])\n\n")

	b.WriteString("export function consoleRegionFor(consoleName: string): 'ntsc_u' | 'ntsc_j' | 'pal' {\n")
	b.WriteString("  const c = consoleName.trim().toLowerCase()\n")
	b.WriteString("  if (c.startsWith('pal ')) return 'pal'\n")
	b.WriteString("  if (c.startsWith('jp ') || JP_CONSOLE_NAMES.has(c)) return 'ntsc_j'\n")
	b.WriteString("  return 'ntsc_u'\n")
	b.WriteString("}\n\n")

	b.WriteString("export const REGION_PLATFORMS: Record<number, Region> = {\n")
	for _, p := range d.Platforms {
		fmt.Fprintf(&b, "  %d: %s,\n", p.IGDBID, tsString(p.Region))
	}
	b.WriteString("}\n\n")

	b.WriteString("export const AVAILABILITY_REGIONS: Record<string, 'ntsc_u' | 'ntsc_j' | 'pal' | 'korea' | 'brazil' | 'china'> = {\n")
	for _, r := range d.ReleaseRegions {
		if r.EntryRegion == "" {
			continue
		}
		fmt.Fprintf(&b, "  %s: %s,\n", r.Name, tsString(r.EntryRegion))
	}
	b.WriteString("}\n")

	return []byte(b.String()), nil
}

func main() {
	yamlPath := flag.String("yaml", "", "path to api/domain.yaml")
	goOut := flag.String("go-out", "", "output path for the generated Go file")
	goPackage := flag.String("go-package", "regionkit", "package name for the generated Go file")
	tsOut := flag.String("ts-out", "", "output path for the generated TypeScript file")
	bundlePath := flag.String("bundle", "", "path to a self-contained (bundled) OpenAPI document, e.g. api/bundled/bff.yaml")
	facetsOut := flag.String("facets-out", "", "output path for the generated facets TypeScript file")
	flag.Parse()

	if *yamlPath == "" || *goOut == "" || *tsOut == "" || *bundlePath == "" || *facetsOut == "" {
		fmt.Fprintln(os.Stderr, "usage: domaingen -yaml <path> -go-out <path> -ts-out <path> -bundle <path> -facets-out <path> [-go-package <name>]")
		os.Exit(2)
	}

	if err := run(*yamlPath, *goOut, *goPackage, *tsOut); err != nil {
		fmt.Fprintln(os.Stderr, "domaingen:", err)
		os.Exit(1)
	}
	if err := runFacets(*bundlePath, *facetsOut); err != nil {
		fmt.Fprintln(os.Stderr, "domaingen:", err)
		os.Exit(1)
	}
}

func run(yamlPath, goOut, goPackage, tsOut string) error {
	data, err := os.ReadFile(yamlPath) //nolint:gosec // G304: yamlPath is a CLI flag from a codegen tool, not untrusted service input.
	if err != nil {
		return fmt.Errorf("reading %s: %w", yamlPath, err)
	}

	d, err := parseDomain(data)
	if err != nil {
		return err
	}

	goSrc, err := generateGo(d, goPackage)
	if err != nil {
		return err
	}
	tsSrc, err := generateTS(d)
	if err != nil {
		return err
	}

	if err := writeFile(goOut, goSrc); err != nil {
		return err
	}
	return writeFile(tsOut, tsSrc)
}

// writeFile creates the destination's parent directory (frontend/src/gen
// does not exist until the first generator run) before writing.
func writeFile(path string, data []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		return fmt.Errorf("creating directory for %s: %w", path, err)
	}
	if err := os.WriteFile(path, data, 0o600); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}
	return nil
}

// --- facets: constraint values mirrored from a bundled OpenAPI document ----
//
// Walks api/bundled/bff.yaml and emits TS "as const" data (maxLength,
// minLength, pattern, minimum, maximum, default) for every schema,
// component parameter, and inline operation parameter. schema.ts is the
// sole enum-value source, so enum keys drop here; a schema whose only
// content besides its enum is "type" gets no entry.
//
// Assumes bundled input: a bare "{ $ref }" in components.schemas or
// components.parameters throws. A $ref nested in a schema's properties
// passes through untouched; a parameter schema that is itself a local
// $ref into components.schemas resolves one level.

// facetKeys are the constraint keys a facet carries; enum is deliberately
// absent (schema.ts is the sole enum-value source).
var facetKeys = []string{"maximum", "minimum", "default", "maxLength", "minLength", "pattern"}

var httpMethods = map[string]bool{
	"get": true, "put": true, "post": true, "delete": true,
	"options": true, "head": true, "patch": true, "trace": true,
}

var localSchemaRefPattern = regexp.MustCompile(`^#/components/schemas/([^/]+)$`)

var facetIdentifierPattern = regexp.MustCompile(`^[A-Za-z_$][A-Za-z0-9_$]*$`)

// facets is buildFacets' result: schemas keyed by name, parameters keyed
// by name, and operation params keyed by operationId then param name.
type facets struct {
	Schemas         map[string]interface{}
	Parameters      map[string]interface{}
	OperationParams map[string]interface{}
}

// parseBundle decodes a bundled document into its dynamic shape: plain
// maps/slices/scalars, since components.schemas nests arbitrary JSON Schema.
func parseBundle(data []byte) (map[string]interface{}, error) {
	var v interface{}
	if err := yaml.Unmarshal(data, &v); err != nil {
		return nil, fmt.Errorf("parsing bundle yaml: %w", err)
	}
	doc, ok := v.(map[string]interface{})
	if !ok {
		return nil, fmt.Errorf("parsing bundle yaml: top-level document is not a mapping")
	}
	return doc, nil
}

// nestedMap walks doc through keys, returning an empty map instead of
// panicking on a missing or wrong-shaped step (like JS's ?. with ?? {}).
func nestedMap(doc map[string]interface{}, keys ...string) map[string]interface{} {
	var cur interface{} = doc
	for _, key := range keys {
		m, ok := cur.(map[string]interface{})
		if !ok {
			return map[string]interface{}{}
		}
		next, present := m[key]
		if !present {
			return map[string]interface{}{}
		}
		cur = next
	}
	m, ok := cur.(map[string]interface{})
	if !ok {
		return map[string]interface{}{}
	}
	return m
}

// refTarget returns node's own "$ref" string and whether it has one.
func refTarget(node interface{}) (string, bool) {
	m, ok := node.(map[string]interface{})
	if !ok {
		return "", false
	}
	ref, ok := m["$ref"].(string)
	return ref, ok
}

// assertNoRef fails when node is a bare "{ $ref: ... }", the signal that
// input is an unbundled spec.
func assertNoRef(node interface{}, where string) error {
	if ref, ok := refTarget(node); ok {
		return fmt.Errorf("domaingen: unresolved $ref at %s (%s); a bundled document should never need one here - is the input actually api/bundled/bff.yaml?", where, ref)
	}
	return nil
}

// resolveParamSchema resolves a schema that is a bare local $ref into
// components.schemas one level deep; any other $ref shape fails loudly.
func resolveParamSchema(schema interface{}, doc map[string]interface{}, where string) (interface{}, error) {
	ref, ok := refTarget(schema)
	if !ok {
		return schema, nil
	}
	var target interface{}
	if match := localSchemaRefPattern.FindStringSubmatch(ref); match != nil {
		target = nestedMap(doc, "components", "schemas")[match[1]]
	}
	if _, ok := target.(map[string]interface{}); !ok {
		return nil, fmt.Errorf("domaingen: unresolvable $ref at %s (%s); a bundled document carries every schema it references - is the input actually api/bundled/bff.yaml?", where, ref)
	}
	return target, nil
}

// extractFacet pulls only facetKeys off a parameter's schema, resolving a
// local vocabulary $ref first (see resolveParamSchema).
func extractFacet(schema interface{}, doc map[string]interface{}, where string) (map[string]interface{}, error) {
	resolved, err := resolveParamSchema(schema, doc, where)
	if err != nil {
		return nil, err
	}
	facet := map[string]interface{}{}
	m, ok := resolved.(map[string]interface{})
	if !ok {
		return facet, nil
	}
	for _, key := range facetKeys {
		if val, present := m[key]; present {
			facet[key] = val
		}
	}
	return facet, nil
}

// stripEnumDeep deep-copies value, dropping every JSON-Schema "enum"
// keyword at any depth - never a field literally named "enum", which
// routes through stripEnumDeepProperties inside a "properties" map instead.
func stripEnumDeep(value interface{}) interface{} {
	switch v := value.(type) {
	case []interface{}:
		out := make([]interface{}, len(v))
		for i, item := range v {
			out[i] = stripEnumDeep(item)
		}
		return out
	case map[string]interface{}:
		out := make(map[string]interface{}, len(v))
		for key, val := range v {
			switch key {
			case "enum":
				continue // the constraint keyword at this level, not a field name
			case "properties":
				out[key] = stripEnumDeepProperties(val)
			default:
				out[key] = stripEnumDeep(val)
			}
		}
		return out
	default:
		return value
	}
}

// stripEnumDeepProperties walks a "properties" map: every key here is a
// field name, never the enum keyword, even one literally named "enum".
func stripEnumDeepProperties(value interface{}) interface{} {
	m, ok := value.(map[string]interface{})
	if !ok {
		return stripEnumDeep(value)
	}
	out := make(map[string]interface{}, len(m))
	for key, val := range m {
		out[key] = stripEnumDeep(val)
	}
	return out
}

// isPureEnumVocabulary reports whether node's only content besides its
// enum is "type" (schema.ts already exports such vocabularies by name).
func isPureEnumVocabulary(node interface{}) bool {
	m, ok := node.(map[string]interface{})
	if !ok {
		return false
	}
	if _, hasEnum := m["enum"]; !hasEnum {
		return false
	}
	for key := range m {
		if key != "enum" && key != "type" {
			return false
		}
	}
	return true
}

// buildSchemaFacets mirrors every components.schemas entry with enum keys
// stripped, omitting a pure enum vocabulary entirely (see isPureEnumVocabulary).
func buildSchemaFacets(schemas map[string]interface{}) (map[string]interface{}, error) {
	out := make(map[string]interface{}, len(schemas))
	for name, node := range schemas {
		if err := assertNoRef(node, fmt.Sprintf("components.schemas.%s", name)); err != nil {
			return nil, err
		}
		if isPureEnumVocabulary(node) {
			continue
		}
		out[name] = stripEnumDeep(node)
	}
	return out, nil
}

// buildParameterFacets emits components/parameters keyed by name; every
// entry gets a facet, even an empty one (no curation).
func buildParameterFacets(parameters map[string]interface{}, doc map[string]interface{}) (map[string]interface{}, error) {
	out := make(map[string]interface{}, len(parameters))
	for name, node := range parameters {
		if err := assertNoRef(node, fmt.Sprintf("components.parameters.%s", name)); err != nil {
			return nil, err
		}
		m, _ := node.(map[string]interface{})
		var schema interface{}
		if m != nil {
			schema = m["schema"]
		}
		facet, err := extractFacet(schema, doc, fmt.Sprintf("components.parameters.%s.schema", name))
		if err != nil {
			return nil, err
		}
		out[name] = facet
	}
	return out, nil
}

// buildOperationParamFacets keeps only inline parameters (a $ref to
// components.parameters is buildParameterFacets' job); no inline params means no entry.
func buildOperationParamFacets(paths map[string]interface{}, doc map[string]interface{}) (map[string]interface{}, error) {
	out := map[string]interface{}{}
	for pathKey, pathItemRaw := range paths {
		pathItem, ok := pathItemRaw.(map[string]interface{})
		if !ok {
			continue
		}
		for method, opRaw := range pathItem {
			if !httpMethods[method] {
				continue
			}
			operation, ok := opRaw.(map[string]interface{})
			if !ok {
				continue
			}
			paramList, ok := operation["parameters"].([]interface{})
			if !ok {
				continue
			}
			operationID, _ := operation["operationId"].(string)
			if operationID == "" {
				continue
			}

			inline := map[string]interface{}{}
			for _, paramRaw := range paramList {
				param, ok := paramRaw.(map[string]interface{})
				if !ok {
					continue
				}
				if _, ok := param["$ref"]; ok {
					continue // components/parameters reference, not inline
				}
				name, _ := param["name"].(string)
				facet, err := extractFacet(param["schema"], doc, fmt.Sprintf("%s %s %s %s", pathKey, method, operationID, name))
				if err != nil {
					return nil, err
				}
				inline[name] = facet
			}

			if len(inline) > 0 {
				if _, dup := out[operationID]; dup {
					return nil, fmt.Errorf("domaingen: duplicate operationId %s", operationID)
				}
				out[operationID] = inline
			}
		}
	}
	return out, nil
}

// buildFacets is the facets job's top-level entry point: parseBundle's
// output in, a facets value out.
func buildFacets(doc map[string]interface{}) (facets, error) {
	schemaFacets, err := buildSchemaFacets(nestedMap(doc, "components", "schemas"))
	if err != nil {
		return facets{}, err
	}
	paramFacets, err := buildParameterFacets(nestedMap(doc, "components", "parameters"), doc)
	if err != nil {
		return facets{}, err
	}
	opFacets, err := buildOperationParamFacets(nestedMap(doc, "paths"), doc)
	if err != nil {
		return facets{}, err
	}
	return facets{Schemas: schemaFacets, Parameters: paramFacets, OperationParams: opFacets}, nil
}

// --- facets: TypeScript literal serialization -------------------------

// serializeFacetValue renders value as a TypeScript literal; object keys
// are sorted (Go map order is randomized), arrays keep source order.
func serializeFacetValue(value interface{}, indent string) string {
	switch v := value.(type) {
	case []interface{}:
		return serializeFacetArray(v, indent)
	case map[string]interface{}:
		return serializeFacetObject(v, indent)
	default:
		return facetJSONLiteral(value)
	}
}

// facetJSONLiteral renders a scalar as JSON, which is also valid
// TypeScript syntax for these types, so no separate TS formatter is needed.
func facetJSONLiteral(value interface{}) string {
	b, err := json.Marshal(value)
	if err != nil {
		// facet scalars are always JSON-safe; this indicates a malformed bundle.
		panic(fmt.Sprintf("domaingen: facet scalar %#v is not JSON-serializable: %v", value, err))
	}
	return string(b)
}

func serializeFacetArray(items []interface{}, indent string) string {
	if len(items) == 0 {
		return "[]"
	}
	allScalar := true
	for _, item := range items {
		switch item.(type) {
		case map[string]interface{}, []interface{}:
			allScalar = false
		}
	}
	if allScalar {
		parts := make([]string, len(items))
		for i, item := range items {
			parts[i] = facetJSONLiteral(item)
		}
		return "[" + strings.Join(parts, ", ") + "]"
	}
	inner := indent + "  "
	lines := make([]string, len(items))
	for i, item := range items {
		lines[i] = fmt.Sprintf("%s%s,", inner, serializeFacetValue(item, inner))
	}
	return "[\n" + strings.Join(lines, "\n") + "\n" + indent + "]"
}

func serializeFacetObject(obj map[string]interface{}, indent string) string {
	if len(obj) == 0 {
		return "{}"
	}
	keys := make([]string, 0, len(obj))
	for key := range obj {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	inner := indent + "  "
	lines := make([]string, len(keys))
	for i, key := range keys {
		lines[i] = fmt.Sprintf("%s%s: %s,", inner, facetJSONLiteral(key), serializeFacetValue(obj[key], inner))
	}
	return "{\n" + strings.Join(lines, "\n") + "\n" + indent + "}"
}

// generateFacetsTS renders facets.ts: as-const exports per schema
// (alphabetical), then parameters and operationParams.
func generateFacetsTS(f facets) ([]byte, error) {
	lines := []string{"// Code generated by domaingen from api/bundled/bff.yaml. DO NOT EDIT.", ""}

	names := make([]string, 0, len(f.Schemas))
	for name := range f.Schemas {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		if !facetIdentifierPattern.MatchString(name) {
			return nil, fmt.Errorf("domaingen: schema name %q is not a valid identifier", name)
		}
		lines = append(lines, fmt.Sprintf("export const %s = %s as const;", name, serializeFacetValue(f.Schemas[name], "")), "")
	}

	lines = append(lines,
		fmt.Sprintf("export const parameters = %s as const;", serializeFacetValue(f.Parameters, "")), "",
		fmt.Sprintf("export const operationParams = %s as const;", serializeFacetValue(f.OperationParams, "")), "",
	)

	return []byte(strings.Join(lines, "\n")), nil
}

// runFacets is the facets job's CLI-level entry point: a bundle path in, an
// output file path out.
func runFacets(bundlePath, facetsOut string) error {
	data, err := os.ReadFile(bundlePath) //nolint:gosec // G304: bundlePath is a CLI flag from a codegen tool, not untrusted service input.
	if err != nil {
		return fmt.Errorf("reading %s: %w", bundlePath, err)
	}
	doc, err := parseBundle(data)
	if err != nil {
		return err
	}
	f, err := buildFacets(doc)
	if err != nil {
		return err
	}
	src, err := generateFacetsTS(f)
	if err != nil {
		return err
	}
	return writeFile(facetsOut, src)
}
